-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 21:40:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Readersdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Readersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Readersdb` DEFAULT CHARACTER SET utf8 ;
USE `Readersdb` ;

-- -----------------------------------------------------
-- Table `Readersdb`.`novels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Readersdb`.`novels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` CHAR(255) NULL,
  `picture` VARCHAR(255) NULL,
  `language` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `synopsis` LONGTEXT NULL,
  `create_date` DATETIME NULL,
  `modified_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Readersdb`.`chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Readersdb`.`chapter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chapter_number` INT NULL,
  `chapter_title` VARCHAR(255) NULL,
  `chapter_body` TEXT NULL,
  `novels_id` INT NOT NULL,
  `create_date` DATETIME NULL,
  `modified_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chapter_novels_idx` (`novels_id` ASC),
  CONSTRAINT `fk_chapter_novels`
    FOREIGN KEY (`novels_id`)
    REFERENCES `Readersdb`.`novels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
